### ISSUE TITLE
Clean up html5 is causing problems with inline js from WP Popular Posts plugin

### ISSUE THREAD

**Issue by jarimbi** [roots/acorn-prettify#12]
### Version

Latest

### What did you expect to happen?

No JS console errors. 

### What actually happens?

The WP Popular posts plugin shows an error i the JS Console of Chrome developer:
wpp.js?ver=6.4.2:121 WPP: Couldn't read JSON data.

And it looks like WooCommerce is also returning some errors in the console.

When I set the config file to  'clean-html5-markup' => false this does not happen anymore.

Is there a way to just exclude the scripting part and still have the other clean-html5-markup features?

### Steps to reproduce

Install acorn prettify and have the plugin Wp Popular Posts active and 'clean-html5-markup' => true in the config file.

Check Chrome developer on a page in the frontend, in the JS Console you'll see the error.

### Please confirm this isn't a support request.

Yes

**Comment by retlehs** [comment]
These steps to reproduce aren't valid — I followed them and I'm not seeing any errors.

> And it looks like WooCommerce is also returning some errors in the console.

...what errors? I'm also not reproduce any issues with this package's clean up feature with WooCommerce, which would be a separate issue anyway

I'm closing this until you can provide actionable steps to prove that there is a bug that this package is responsible
