### ISSUE TITLE
`No publishable resources for tag [prettify-config]`

### ISSUE THREAD

**Issue by strarsis** [roots/acorn-prettify#6]
### Version

v1.0.1

### What did you expect to happen?

The config file should be published.

### What actually happens?

No config file published, info message that there is no publishable resource for tag `[prettify-config]`.

### Steps to reproduce

1. Require `acorn-prettify` in a Sage 10 theme: `composer require roots/acorn-prettify`.
2. Invoke the WP CLI command to publish the config file: `wp acorn vendor:publish --tag=prettify-config`.

### System info

Ubuntu 22 LTS on WSL 2 / Windows 10.

### Log output

```shell
INFO  No publishable resources for tag [prettify-config].
```

### Please confirm this isn't a support request.

Yes

**Comment by Log1x** [comment]
Hmm, it seems to be working for me.

```
~/sites/sage
❯ wp acorn vendor:publish --tag=prettify-config

   INFO  Publishing [prettify-config] assets.

  Copying file [/Users/brandon/Sites/sage/vendor/roots/acorn-prettify/config/prettify.php] to [config/prettify.php] ....................... DONE
```

Did you install it alongside Acorn where you have your [post-install-scripts](https://roots.io/acorn/docs/installation/#installing-acorn-with-composer)? Try running `wp acorn optimize:clear`

**Comment by strarsis** [comment]
> wp acorn optimize:clear

This fixed it:
````
Cannot publish [[...]/themes/[...]/vendor/roots/acorn-prettify/src/../config/prettify.php] until Acorn is initialized.

 Would you like to initialize Acorn right now? (yes/no) [yes]:
 > yes
 
 Initialized [[...]/themes/[...]/config]
  Copying file [vendor/roots/acorn-prettify/config/prettify.php] to [config/prettify.php]  DONE

````

After invoking `wp acorn optimize:clear` the error went away.

For whatever reason `acorn` was not initialized yet?

This is in the theme `composer.json`:
```json
[...]
  "extra": {
    "acorn": {
      "providers": [
        "App\\Providers\\ThemeServiceProvider"
      ]
    }
  },
  "post-autoload-dump": [
    "Roots\\Acorn\\ComposerScripts::postAutoloadDump"
  ]
````
